# Deployment for pushes to main
name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
    # branches:
    #   - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: npm ci
      - run: npm run build
      - run: npx vercel pull --yes
      - run: npx vercel build
      - uses: amondnet/vercel-action@v20 # Deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional 
          vercel-args: '--prebuilt --prod' # Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  # Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} # Required
